x = input('请输入一个数值')
x0 = x.count('0')
x1 = x.count('1')
x2 = x.count('2')
x3 = x.count('3')
x4 = x.count('4')
x5 = x.count('5')
x6 = x.count('6')
x7 = x.count('7')
x8 = x.count('8')
x9 = x.count('9')
print('数字0出现%d'%x0 )
print('数字1出现%d'%x1 )
print('数字2出现%d'%x2 )
print('数字3出现%d'%x3 )
print('数字4出现%d'%x4 )
print('数字5出现%d'%x5 )
print('数字6出现%d'%x6 )
print('数字7出现%d'%x7 )
print('数字8出现%d'%x8 )
print('数字9出现%d'%x9 )